### ISSUE TITLE
Rebuild with custom userimg.jl?

### ISSUE THREAD

**Issue by mlhetland** [staticfloat/homebrew-julia#117]
If one adds a `userimg.jl` file with `require` statements in the `base` subdirectory of the install and rebuilds Julia, one can get cached, precompiled versions of modules one might use often. Highly useful. And … if one already uses Homebrew to build Julia, it would be very useful if one could somehow manage to do this with the requisite Homebrew formula…

Is there any way you could add something like that? Perhaps some environment variable indicating a `userimg.jl` file to be copied in, or some extra switch to the build command or something? (I'm a Homebrew n00b, so I don't know if there's a standard way of doing something like this…)

**Comment by mlhetland** [comment]
OK, revisiting this again.

- Currently can't get the `--userimg` switch to work
- Julia now ships with [an in-julia mechanism](http://docs.julialang.org/en/release-0.3/devdocs/sysimg/) sort of for rebuilding the sysimg.
- There are issues with using that with the homebrew-installed Julia

The first point: I haven't worked too hard on figuring out what's going on there, as the whole switch is probably a lot less useful now, anyway, with the more standard (albeit probably stop-gap) mechanism. The issue with `build_sysimg` seems to be just that it can't overwrite the existing image at the default location. Once I did
```
$ chmod u+w /usr/local/Cellar/julia/0.3.7/lib/julia/sys.*
```
it works. I.e., I can run the following to rebuild with my userimg:
```
include(joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl"))
build_sysimg(default_sysimg_path, "native", usrimg; force=true)
```
It also works if I install the sysimg elsewhere, and load it manually with the `-J` switch. One might think this is the Right Thing™ to do, but `chmod`-ing the existing `sys.*` files yields the following conclusion to the rebuild:
```
INFO: Linking sys.dylib
INFO: System image successfully built at /usr/local/Cellar/julia/0.3.7/lib/julia/sys.dylib
INFO: Julia will automatically load this system image at next startup
```
I.e., it seems this is a scenario that should be possible. (I even seem to think it worked earlier?)

So:

- Perhaps the formula should adjust the write permissions (i.e., `u+w` for the existing `sys.*` files)?
- Perhaps we should point to `build_sysimg` rather than maintaining/fixing the `--userimg` switch? (Or we could just leave that; I guess I may just be having compile trouble in general.)

For now, though, I can always just add a `chmod` in my rebuild script. Adding something about that in the `README` might also be an option, perhaps.

**Comment by staticfloat** [comment]
I agree with you; we should `chmod` the `sys.*` files.  It looks like homebrew is changing the permissions behind our backs, I imagine it's a "best practices" type of thing, as you typically wouldn't change your files in `lib/`.  Once we do that, I also think we should remove the `--userimg` switch, since it does seem like the `build_sysimg.jl` script should do everything we need it to.
