### ISSUE TITLE
Building libMagickWand segfaults

### ISSUE THREAD

**Issue by jwmerrill** [staticfloat/homebrew-julia#142]
Log here: https://gist.github.com/jwmerrill/5287fdbe24a6b06fa4eb

```
julia> versioninfo()
Julia Version 0.3.2
Commit 8227746 (2014-10-21 22:05 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by staticfloat** [comment]
This is probably in the wrong repository, (Should be [homebrew-juliadeps](https://github.com/staticfloat/homebrew-juliadeps)) but that's fine, we can work it out here.

Can you do the following and post the resultant output:

```
using Homebrew
Homebrew.rm("imagemagick")
Homebrew.update()
Homebrew.add("imagemagick")
Pkg.build("Images")
```

**Comment by jwmerrill** [comment]
That worked fine. I guess there must have been some bad state sitting around somewhere. Thanks for your help.

For posterity, here's the terminal session showing this working: https://gist.github.com/jwmerrill/1815ca446208c490400b

**Comment by staticfloat** [comment]
I seemed to remember this popping up before; I'm glad this worked!  Please don't hesitate to open similar issues in the future.
