### ISSUE TITLE
Error building `--HEAD`

### ISSUE THREAD

**Issue by dpo** [staticfloat/homebrew-julia#146]
`brew install -v julia --HEAD` fails with
````
Exception occurred:
  File "conf.py", line 16, in <module>
    import juliadoc
ImportError: No module named juliadoc
````
Skimming through past issues, I did `rm -rf $(brew --cache)/julia--git`, but that didn't do it.

**Comment by staticfloat** [comment]
That would indeed have been my first guess at what to do as well.  Unfortunately, I can't reproduce this locally.  Have you done a `brew update` recently?

**Comment by dpo** [comment]
I `brew update` several times a day. Interestingly, the build succeeded on a Yosemite machine. The failure occurred on Mavericks. Something is might be at play and it's probably due to something local.

**Comment by staticfloat** [comment]
I see.  Next time I'm around a Mavericks computer I'll try to see if this is a Mavericks-specific problem, but until then, I'm not sure what to try next.

**Comment by dpo** [comment]
Thanks. I'll close this and will reopen if need be.
