### ISSUE TITLE
Error building Julia from HEAD

### ISSUE THREAD

**Issue by ZacCranko** [staticfloat/homebrew-julia#155]
Hi there,

I'm getting the following error after updating and upgrading brew then running `brew install julia --HEAD`
```
==> make prefix=/usr/local/Cellar/julia/HEAD USE_BLAS64=0 FC=/usr/local/bin/gfort
main at /private/tmp/julia20150605-33479-v29a0u/usr/bin/julia (unknown line)

*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/private/tmp/julia20150605-33479-v29a0u/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/staticfloat/homebrew-julia/issues
```

Any ideas?

**Comment by tkelman** [comment]
Would be good to post the entire error, and/or gist the build logs.

**Comment by ZacCranko** [comment]
I made this https://gist.github.com/f1a89516d106ee3d42f8 is that what you're after?

**Comment by tkelman** [comment]
Yeah that helps.
```
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Operation timed out
 
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Operation timed out
 
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Operation timed out
 
make[1]: *** [libuv] Error 128
make[1]: *** Waiting for unfinished jobs....
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Operation timed out
 
make[1]: *** [openlibm] Error 128
make[1]: *** [openspecfun] Error 128
make[1]: *** [utf8proc] Error 128
make: *** [julia-deps] Error 2
```

Is the `git://` protocol blocked on your network?

**Comment by ZacCranko** [comment]
Nope, though this is not the error I got before, I'll try to reproduce it and gist the build log.

**Comment by ZacCranko** [comment]
Ah, here we go this is what I was seeing before https://gist.github.com/3ba9e02c5597f2e69199

**Comment by tkelman** [comment]
That's because of the PCRE2 upgrade on master. We just need to change the pcre dependency to pcre2 for building HEAD.

**Comment by ZacCranko** [comment]
I have no idea what that is but cool.

**Comment by tkelman** [comment]
hyar https://github.com/staticfloat/homebrew-julia/blob/81e7c5550b0ce6a8dd38e74cbcd5c02990bb5c8a/julia.rb#L52

Need to be changed to something like
```
depends_on "pcre" if not build.head?
depends_on "pcre2" if build.head?
```
but I'm not positive on the syntax there. Care to try it, see if it fixes HEAD and doesn't break 0.3?

**Comment by ZacCranko** [comment]
Made the modification then did a `brew reinstall julia --HEAD` then a `brew reinstall julia` to check v0.3 was still working. No problems on either! Nice one.

**Comment by ZacCranko** [comment]
Possibly off topic, but do you know if it's possible to have v0.4 and v0.3 installed at the same time?

**Comment by tkelman** [comment]
Since you tested it, care to open the PR for that?

Yes if you install 0.4 and 0.3 to different locations/names it is possible to have them installed at the same time, but I'm not sure about through homebrew.

**Comment by staticfloat** [comment]
In Homebrew, you can have multiple versions installed in their own "keg", (e.g. they will be installed to `/usr/local/Cellar/julia/VERISON`, where `VERSION` is something like `0.3.9` or `HEAD`) but only one can be "linked", which means that its files will appear in `/usr/local/bin`, `/usr/local/share`, etc....

This means that while you can have both installed at once, when you type `julia`, only one will be on the default search path.  If you want to switch between the two, you can use `brew switch julia 0.3.9` and `brew switch julia HEAD`.  This will "unlink" the currently linked keg and link in the new version.

**Comment by ZacCranko** [comment]
Great tip, cheers.
