### ISSUE TITLE
Julia head fails to install

### ISSUE THREAD

**Issue by spott** [staticfloat/homebrew-julia#159]
https://gist.github.com/spott/4cea4d2a506f2c333a24

It looks like the install script is failing?

```
# Copy system image
/private/tmp/julia20150623-63350-zv8qpy/contrib/install.sh 644 /private/tmp/julia20150623-63350-zv8qpy/usr/lib/julia/sys.ji /usr/local/Cellar/julia/HEAD/lib/julia
cp: /private/tmp/julia20150623-63350-zv8qpy/usr/lib/julia/sys.ji: No such file or directory
make: *** [install] Error 1
```

**Comment by staticfloat** [comment]
Yep, good catch.  As a matter of fact, ALL platforms are currently failing. See this comment: https://github.com/JuliaLang/julia/pull/11640#issuecomment-114574852

**Comment by ZacCranko** [comment]
Any progress on this?

**Comment by staticfloat** [comment]
See https://github.com/JuliaLang/julia/pull/11854 for a potential fix waiting to be merged.

**Comment by IainNZ** [comment]
This is fixed now?

**Comment by staticfloat** [comment]
Yes, this should be fixed.

**Comment by IainNZ** [comment]
If my install is borked due to 
```
ld: file not found: /usr/local/lib/gcc/4.9/libgfortran.3.dylib for architecture x86_64
```
is there a good way to recover it?

**Comment by staticfloat** [comment]
Yes, `brew rm --force openblas-julia; brew install openblas-julia` should fix it.

**Comment by IainNZ** [comment]
Oh just spotted the help at the top
