### ISSUE TITLE
Julia Install Fails on 10.7.5 with patch error

### ISSUE THREAD

**Issue by BobTheBotMaker** [staticfloat/homebrew-julia#164]
The patch located at `staticfloat/4f8248add3ed27ba250c/raw/0d180c11d4131a53c3361d71ba21aac3f0ef343e/Makefile.diff` fails to apply to the brach of Julia that was checked out on my machine.

A git log says its the v0.3.10 tag, however upon inspection of the Juila Makefile and the .diff, the lines do not match up. The diff looks like it would apply to the latest julia head but in 0.3.10 those lines are on line 180 not 236 of the Makefile. Should there be two versions of the patch ?

Thanks

**Comment by staticfloat** [comment]
This should be fixed by Zac's PR #165.  Please `brew update` and try again.
