### ISSUE TITLE
Julia failed to build on 10.9.5

### ISSUE THREAD

**Issue by dunn** [staticfloat/homebrew-julia#167]
_From @joeguinness on August 27, 2015 20:4_

https://gist.github.com/anonymous/a519fa135fb2be54ba12

Julia 0.4 had been installed on my computer with homebrew. During troubleshooting on how to get the most recent build of julia, I ran 

brew rm julia
brew install --HEAD julia

which gave me a warning:
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

I had some software installed on my computer a few months ago using macports, so I went and uninstalled macports using these instructions:
https://guide.macports.org/chunked/installing.macports.uninstalling.html

Then I tried again to install julia with "brew install --HEAD julia", which still did not work. The gist link above is for this most recent install.

_Copied from original issue: Homebrew/homebrew#43337_

**Comment by dunn** [comment]
Unrelated to this build failure, but it looks like the build script is downloading additional resources (https://gist.github.com/anonymous/a519fa135fb2be54ba12#file-04-make-L28)—it'd be ideal for those to be vendored in the formula.

**Comment by staticfloat** [comment]
Interesting.  @joeguinness, do you know where your `python` install is coming from?

**Comment by joeguinness** [comment]
I have anaconda. Is that what you're asking?

**Comment by staticfloat** [comment]
Ahh, yep.  I see that your `python` is `/anaconda/bin/python`, and not `/usr/bin/python` as is typical.

It looks to me like the problem you're hitting is actually with python, not Julia:

```
Installing setuptools, pip...
  Complete output from command /private/tmp/julia20...julia-env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/julia20150827-66083-b1bajs/deps/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "/private/tmp/julia20150827-66083-b1bajs/deps/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/log.py", line 8, in <module>
  File "/private/tmp/julia20150827-66083-b1bajs/deps/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/backwardcompat/__init__.py", line 66, in <module>
  File "/anaconda/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/anaconda/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/anaconda/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/private/tmp/julia20150827-66083-b1bajs/deps/julia-env/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /private/tmp/julia20150827-66083-b1bajs/deps/julia-env/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup
```

My guess would be that it's Anaconda's python that is giving this `pip` install trouble.  @stevengj do you have any wisdom to give here?  Is there a way we could force Julia's install to use the system python instead of Anaconda's python in order to see if that fixes the problem?

**Comment by joeguinness** [comment]
I simply commented out the line in my .bash_profile that added //anaconda to the path, then restarted, then ran "brew install --HEAD julia" again, and it worked just fine. Thanks for all your help. One question: will using the system python (instead of anaconda) cause any problems for me?

**Comment by staticfloat** [comment]
Now that you have finished installing Julia, you should be able to uncomment that line and everything will "just work".  In general, there is no interaction between Julia and Python after the build is done.  (The exception is when you ask for it, using packages like `IJulia` which uses python code to run the notebook server, or `PyCall`, etc...)  Therefore, you shouldn't have to worry about using system python or anaconda python after it's installed.  Do whatever you want to.

**Comment by staticfloat** [comment]
I'm going to assume that this issue has been dealt with on your end, if you continue to have issues, please do not hesitate to open a new issue.
