### ISSUE TITLE
brew install --HEAD julia failed due to outdated patch files

### ISSUE THREAD

**Issue by timxzl** [staticfloat/homebrew-julia#171]
to use with the HEAD version of Julia, the two patch files should be like:
https://gist.githubusercontent.com/timxzl/acbe3404c4bdb30e1aa9/raw/6a612309ebaac7829e6c138a35e43ea0a49fa994/deps.Makefile.diff
https://gist.githubusercontent.com/timxzl/c6f474fa387382267723/raw/2ecb0270d83f0a167358ff2a396cd6004e1b02a0/Makefile.diff

needs to add head? check to select the appropriate patch files

**Comment by staticfloat** [comment]
Thank you, @timxzl!  Very helpful.  I'm going to keep the patches pointed at your gists, so you get all the glory for this fix.  :)

**Comment by timxzl** [comment]
thanks, @staticfloat for fixing the tap! This would greatly ease the job of installing Julia on OS X!
and thanks for glorifying! I feel honored.
