### ISSUE TITLE
arpack-julia download fails

### ISSUE THREAD

**Issue by floringogianu** [staticfloat/homebrew-julia#173]
`brew install -v arpack-julia` fails because 
```
curl -fLA http://forge.scilab.org/index.php/p/arpack-ng/downloads/get/arpack-ng-3.1.3.tar.gz -C 0 -o
``` 
returns a 403 forbidden and
```
curl -fLA http://d304tytmzqn1fl.cloudfront.net/arpack-ng-3.1.3.tar.gz -C 0 -o
```
returns a 404 not found.

**Comment by staticfloat** [comment]
Thanks for this @floringogianu, I have updated `arpack-julia` and given it a new, more reliable download site.

**Comment by jenshnielsen** [comment]
This still happens, both the main and mirror download sites are down. I also don't see any changes to the arpack-julia formula in the last 5 month

**Comment by jenshnielsen** [comment]
I'm trying to install on 10.11 where there are no bottles

**Comment by staticfloat** [comment]
Please `brew update` and try again.

**Comment by jenshnielsen** [comment]
Works now. Thanks

**Comment by floringogianu** [comment]
Thanks @staticfloat !
