### ISSUE TITLE
Option to install RC versions

### ISSUE THREAD

**Issue by makokal** [staticfloat/homebrew-julia#175]
Can we have additional options to install rc versions instead of having to pick only between `stable` and `HEAD` as it is at the moment?

**Comment by jongwook** [comment]
and could anyone update Julia 0.4.0 to `stable`?

**Comment by ntdef** [comment]
+1 to Julia 4 stable

**Comment by StefanKarpinski** [comment]
I'm happy to see everyone so eager. I'm sure that @staticfloat will do this just as soon as he has a chance. Thanks for the patience!

**Comment by ronubi** [comment]
Does anybody use `brew-cask` instead of `brew` to keep Julia current? I'm thinking of switching, but I noticed that the cask maintainer is also stuck on v0.3.11.

**Comment by staticfloat** [comment]
The reason v0.4 hasn't been released yet is because the OSX buildbots have been having some trouble building the bottles, but fear not, we're working on it.  :)

**Comment by ntdef** [comment]
@staticfloat sweet! thanks for all your work!

**Comment by staticfloat** [comment]
Looks like I managed a breakthrough!  How's it look for you guys?  `brew update` and then `brew install julia`.  Note that bottles for El Capitan are not yet available.

**Comment by makokal** [comment]
Works like a charm on Yosemite,  Thanks @staticfloat

**Comment by ronubi** [comment]
`el-cap$ brew update`
`el-cap$ brew upgrade`

worked today on OS X El Capitan v10.11 – installed Julia v0.4 with no apparent issues.  I copied the `v0.3/REQUIRE` file and 

`julia> Pkg.update()`

restored all my packages.

Thanks!  About to test with `jupyter-notebook` ...

**Comment by staticfloat** [comment]
Now that `v0.4.1` is out; is there anything further that needs discussion here?  I don't know of an easy way for me to add more options to the `julia` formula beyond `stable` and `head` for things like RC builds, but I'm open to suggestions.
