### ISSUE TITLE
Tests of bottled julia 0.4.0 failing because of missing libgit2 dependency

### ISSUE THREAD

**Issue by ahonkela** [staticfloat/homebrew-julia#183]
The libgit2 test fails on bottled julia 0.4.0 fail if libgit2 is not installed. Perhaps we should either add libgit2 as a dependency or disable the corresponding functionality and test.

This appears highly related to #181 but submitting as new as I this does not seem to fit under the same title and I do not think I can change the title.

**Comment by floringogianu** [comment]
@ahonkela Yes, is the same. Strange is that the built from sources version passes the tests. Also, on which os you are getting this? I was under the impression that is on ElCapitan only.

**Comment by ahonkela** [comment]
I am still on Yosemite.

This is just speculation, but maybe building from source detects the missing libgit2 dependency and disables the corresponding test. The machine used to build the bottled version probably has the libgit2 package installed and thus works assuming it will be available.

**Comment by staticfloat** [comment]
Thank you for alerting me to this issue.  I've pushed a new version of the `julia` formula, new installs from here on out should require `libgit2` when installing; if you have already installed `julia`, it's possible you will need to `brew install libgit2` manually for this test to pass.
