### ISSUE TITLE
Issue with gmp4-julia compilation

### ISSUE THREAD

**Issue by superxuxin** [staticfloat/homebrew-julia#193]
ld: .libs/libgmp.la-420.o: relocation R_X86_64_32 against `__gmp_sscanf_funs' can not be used when making a shared object; recompile with -fPIC
.libs/libgmp.la-420.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libgmp.la] Error 1

gcc (Homebrew gcc 5.2.0) 5.2.0

Please help...

**Comment by staticfloat** [comment]
What brought you to this error?  What are you trying to compile?

**Comment by superxuxin** [comment]
I am trying to compile julia. It requires gmp4-julia I believe. I already have gmp 6 installed, but I don't know how to make julia use gmp 6 for compilation. I cannot get gmp4-julia complied either as the error shows. Thank you for your help.

**Comment by staticfloat** [comment]
What version of OS X are you running?  What does `brew doctor` say?

**Comment by staticfloat** [comment]
Please `brew update` and try again, this should be fixed now.
