### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by chernals** [staticfloat/homebrew-julia#201]
I tried `brew install --HEAD --64bit julia` and got the following error.

Is the error apparent or obvious or should I provide more detaills?

Thanks in advance!

==> Cloning https://github.com/JuliaLang/julia.git
Cloning into '/Library/Caches/Homebrew/julia--git'...
remote: Counting objects: 165004, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 165004 (delta 12), reused 0 (delta 0), pack-reused 164979
Receiving objects: 100% (165004/165004), 92.86 MiB | 4.73 MiB/s, done.
Resolving deltas: 100% (125730/125730), done.
Checking connectivity... done.
==> Checking out branch master
Cloning into '/private/tmp/julia20160113-86833-f47oyn'...
done.
==> Downloading https://gist.githubusercontent.com/timxzl/c6f474fa387382267723/r
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/timxzl/acbe3404c4bdb30e1aa9/r
######################################################################## 100.0%
==> Patching
patching file Makefile
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 278 with fuzz 1 (offset 6 lines).
patching file deps/Makefile
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 1675 with fuzz 1 (offset 6 lines).
==> make -C contrib -f repackage_system_suitesparse4.make prefix=/usr/local/Cell
==> make prefix=/usr/local/Cellar/julia/HEAD USE_BLAS64=0 FC=/usr/local/bin/gfor
Last 15 lines from /Users/chernals/Library/Logs/Homebrew/julia/02.make:
make[1]: *** [build/libosxunwind-0.0.3/libosxunwind.dylib] Error 2
make[1]: *** Waiting for unfinished jobs....
warning: --depth is ignored in local clones; use file:// instead.
Note: checking out '3ee2a6e6a9fc68cbf2ab00f830b9059215e40b06'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

make: *** [julia-deps] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/staticfloat/homebrew-julia/issues

**Comment by staticfloat** [comment]
Hmmm, it's somewhat mysterious.  Could you run the same thing but add the `--verbose` flag so we can see a little more of what's going on?

**Comment by chernals** [comment]
Thanks for your reply.

I ran it again with —verbose and strangely enough it seems to have worked.

 » brew test -v julia
Testing staticfloat/julia/julia
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160115-83058-wp8ghw.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/staticfloat/homebrew-julia/julia.rb -v —HEAD


Should I conclude that it’s all fine?

**Comment by staticfloat** [comment]
Sounds like perhaps `master` on JuliaLang/julia was broken.  Glad to hear it's working!
