### ISSUE TITLE
Upgrade to Julia 0.4.3

### ISSUE THREAD

**Issue by essenciary** [staticfloat/homebrew-julia#203]
Can you please add support to get the upgrade to Julia 0.4.3? Thanks! 

```
brew info julia
staticfloat/julia/julia: stable 0.4.2 (bottled), HEAD
http://julialang.org
/usr/local/Cellar/julia/0.4.2 (675 files, 122.7M) *
  Poured from bottle
From: https://github.com/staticfloat/homebrew-julia/blob/master/julia.rb
==> Dependencies
Required: staticfloat/julia/llvm33-julia ✔, pcre2 ✔, gmp ✔, fftw ✔, mpfr ✔, libgit2 ✔, staticfloat/julia/arpack-julia ✔, staticfloat/julia/openblas-julia ✔, staticfloat/julia/suite-sparse-julia ✔
```

**Comment by JeremyCavanagh** [comment]
I am also waiting for this new version. However, one must have patience. I recall that the previous upgrade to brew was at least two weeks after the release and we are currently only 11 days after the release. Afterall, the guys who are doing this great work for us are doing so out of the kindness of their hearts and not as far as I am aware for monetary gain. Just the glory and thanks from the community.

As they used to say in the good ol' days 'Keep on truckin'.

**Comment by staticfloat** [comment]
Thanks for the patience guys, after some difficulty with the buildbots, I have bottled `0.4.3`.  Please `brew update` and see if there is an updated Julia waiting for you!  You can upgrade `julia` by running `brew upgrade julia` after running `brew update`.

**Comment by JeremyCavanagh** [comment]
Hi Elliot,

Thanks for the effort, but, unfortunately 0.4.3 is not showing up.

**Comment by staticfloat** [comment]
Ah, sorry, I forgot to merge `staging` into `master`.  Please try again now.

**Comment by JeremyCavanagh** [comment]
Yippeeee,

Thanks

**Comment by essenciary** [comment]
Just upgraded, worked like a charm! Cheers!
