### ISSUE TITLE
behind the times?

### ISSUE THREAD

**Issue by tcovert** [staticfloat/homebrew-julia#206]
any particular reason why homebrew-julia is still at 0.4.3, while the current release is 0.4.5?  just curious...

**Comment by StefanKarpinski** [comment]
Lack of manpower to update homebrew-julia. I.e. @staticfloat is busy (quite understandably).

**Comment by staticfloat** [comment]
There have also been some issues with our OSX binary build infrastructure. We're in the process of purchasing new hardware, so for the moment please hold tight, we'll get 0.4.5 bottled and ready for you soon!

**Comment by staticfloat** [comment]
`brew update` and `brew upgrade`; you should get the latest!  Please open an issue for any new problems you encounter!
