### ISSUE TITLE
'libcholmod' not getting loaded

### ISSUE THREAD

**Issue by vishaluk** [staticfloat/homebrew-julia#208]
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libcholmod"
dlopen(libcholmod.dylib, 1): Library not loaded: /usr/local/opt/openblas-julia/lib/libopenblasp-r0.2.17.dylib
  Referenced from: /usr/local/Cellar/julia/0.4.5/lib/julia//libcholmod.dylib
  Reason: image not found")
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin15.4.0

I am using mac with el capitan and upgraded Julia from 0.4.0 to 0.4.5 and now I get the error about unable to load 'libcholmod'. I have done the brew update but that didnt help.

**Comment by staticfloat** [comment]
What does `brew info openblas-julia` show?  You can try `brew rm -f openblas-julia` followed by `brew install openblas-julia`.

**Comment by staticfloat** [comment]
I'm closing this, as this issue should be resolved.
