### ISSUE TITLE
Permission denied for brew rm

### ISSUE THREAD

**Issue by okvs** [staticfloat/homebrew-julia#209]
I am suddenly encountering a permission problem when uninstalling julia HEAD (in order to update):
```
$ brew rm julia
Error: Permission denied - /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib.dSYM/Contents
```
I have no problems updating homebrew itself, upgrading (other) packages and so on, and have happily been installing and updating julia previously. `brew rm whatever` works -- but not for Julia.

Versioninfo:
```
Version 0.5.0-dev+3880 (2016-05-04 19:59 UTC)
Commit 9caa28d* (26 days old master)
```
on os x 10.11.2.

**Comment by okvs** [comment]
Well I tried a lot of different things that did not work, repair permissions, `sudo chown`, all sorts of `brew doctor` stuff.. In the end a simple `chmod` helped, and I was able to uninstall.

Reinstalling HEAD also worked on the second attempt, but at the end of installation I got the following summary:
```
==> Summary
Error: Permission denied - /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib.dSYM/Contents
```
Now, the installation finished, Julia starts and seems to work, but this permission thing is weird. Can anyone explain what's going on? Should I just `chmod` it every time from now on?

**Comment by staticfloat** [comment]
This looks like it might actually be a Julia bug.  I remember running into this a few times in the past, but not having the time to track it down.  I will be taking a look at this in the near future, thank you for reporting!

**Comment by staticfloat** [comment]
I've pushed a small fix, please `brew update` and try again whenever you feel like it.  Of course, at the moment, I think Julia `master` is broken. ;)

**Comment by staticfloat** [comment]
This should be fixed now.

**Comment by kirk86** [comment]
This is still an issue. Is not fixed:

```
brew uninstall julia
Error: Permission denied @ rb_file_s_lstat - /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib.dSYM/Contents
```
