### ISSUE TITLE
Problem on brew upgrade: curl: (56) SSLRead() return error -9806

### ISSUE THREAD

**Issue by kamalasaurus** [staticfloat/homebrew-julia#217]
Hi, there seems to be a problem pulling down the arpack-julia dependency.  The issue appears to be specific to openblas-julia, maybe it triggered a timeout or something.  Just thought I'd let you know in case it's something relevant.

<img width="816" alt="screen shot 2016-08-02 at 11 21 21 pm" src="https://cloud.githubusercontent.com/assets/2119142/17334186/e1b457ba-5907-11e6-8d11-ebb03fe808e2.png">

**Comment by staticfloat** [comment]
Hmmmm..... what happens if you navigate there in your browser?  (E.g. visit [this link](https://juliabottles.s3.amazonaws.com/openblas-julia-0.2.18.el_capitan.bottle.tar.gz)). Alternatively, can you post the following output:

```
$ curl -v https://juliabottles.s3.amazonaws.com/openblas-julia-0.2.18.el_capitan.bottle.tar.gz -o /dev/null

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 54.231.11.112...
* Connected to juliabottles.s3.amazonaws.com (54.231.11.112) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.s3.amazonaws.com
* Server certificate: DigiCert Baltimore CA-2 G2
* Server certificate: Baltimore CyberTrust Root
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /openblas-julia-0.2.18.el_capitan.bottle.tar.gz HTTP/1.1
> Host: juliabottles.s3.amazonaws.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2: ddmozFoRniqEIpOfAhNHmL2x8VkSKjUjZylzKyj0lgEe/i8pwd6qYQCVccr5fSCx
< x-amz-request-id: 30C0D0DC54EF70B3
< Date: Sat, 06 Aug 2016 21:18:30 GMT
< Last-Modified: Wed, 08 Jun 2016 23:19:19 GMT
< ETag: "daafedc158c2a6bb233984b7e4579ff5"
< Accept-Ranges: bytes
< Content-Type: binary/octet-stream
< Content-Length: 19778004
< Server: AmazonS3
<
{ [16384 bytes data]
100 18.8M  100 18.8M    0     0   411k      0  0:00:46  0:00:46 --:--:--  847k
* Connection #0 to host juliabottles.s3.amazonaws.com left intact
```

**Comment by kamalasaurus** [comment]
It seems to work fine when I do it through the browser; the output from
curl is included (also seems to work).

Maybe it was some random network hiccup?

curl -v
https://juliabottles.s3.amazonaws.com/openblas-julia-0.2.18.el_capitan.bottle.tar.gz
-o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0*   Trying 52.216.1.64...
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0* Connected to juliabottles.s3.amazonaws.com (52.216.1.64) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.s3.amazonaws.com
* Server certificate: DigiCert Baltimore CA-2 G2
* Server certificate: Baltimore CyberTrust Root
> GET /openblas-julia-0.2.18.el_capitan.bottle.tar.gz HTTP/1.1
> Host: juliabottles.s3.amazonaws.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2:
pV6LuxsHHFEo7k63z7/oTGCXK/5qcu5MD0gr0/knC3VqLx+0igeoZoaCymrBRGi3hXLTLhT96Qk=
< x-amz-request-id: 804E46A3AAA038EA
< Date: Sun, 07 Aug 2016 08:33:41 GMT
< Last-Modified: Wed, 08 Jun 2016 23:19:19 GMT
< ETag: "daafedc158c2a6bb233984b7e4579ff5"
< Accept-Ranges: bytes
< Content-Type: binary/octet-stream
< Content-Length: 19778004
< Server: AmazonS3
<
  0 18.8M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--
  0{ [16384 bytes data]

**Comment by staticfloat** [comment]
Yes, I'm inclined to think it was a network hiccup.  Let us know it if happens again.
