### ISSUE TITLE
BottleSpecification#sha1 is deprecated

### ISSUE THREAD

**Issue by cbischoff** [staticfloat/homebrew-julia#219]
I get the following warnings every time I run brew:

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/gmp4-julia.rb:9:in `<class:Gmp4Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/gmp4-julia.rb:9:in `<class:Gmp4Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/gmp4-julia.rb:9:in `<class:Gmp4Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/gmp4-julia.rb:15:in `block in <class:Gmp4Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/gmp4-julia.rb:16:in `block in <class:Gmp4Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:9:in `block in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:9:in `block in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:13:in `block (2 levels) in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:18:in `block (2 levels) in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:23:in `block (2 levels) in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:28:in `block (2 levels) in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:33:in `block (2 levels) in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:66:in `block in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Library/Taps/staticfloat/homebrew-julia/llvm33-julia.rb:67:in `block in <class:Llvm33Julia>'
Please report this to the staticfloat/julia tap!

**Comment by cbischoff** [comment]
Sorry, only happens when I run `brew update` and it actually pulls a new update. If I get `Already up-to-date.` there are no warnings.

**Comment by staticfloat** [comment]
This should now be fixed by your latest `brew update`.  Let us know if it happens again.
