### ISSUE TITLE
Oh my, zero-point-five! 

### ISSUE THREAD

**Issue by essenciary** [staticfloat/homebrew-julia#220]
@staticfloat No rush, but just a quick reminder that the mac brewsters are avidly waiting for the goodies. Thank you! ♥️

![ghw6bt6rzs-18](https://cloud.githubusercontent.com/assets/11292378/18679483/13aff8a4-7f60-11e6-95b2-ec22025e2980.png)

**Comment by staticfloat** [comment]
Rush or not, it's here!  Wahooo! https://github.com/staticfloat/homebrew-julia/pull/221

**Comment by essenciary** [comment]
You rock! 🕶
