### ISSUE TITLE
julia 0.5.0 fails to build on OS X 10.12

### ISSUE THREAD

**Issue by tdsmith** [staticfloat/homebrew-julia#222]
Error appears early on:
```
clang: error: no such file or directory: 'libosxunwind.a'
make[2]: *** [libosxunwind.dylib] Error 1
...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libosxunwind.a(Unwind-sjlj.c.o) has no symbols
make[1]: *** [build/libosxunwind-0.0.3/libosxunwind.dylib] Error 2
make[1]: *** Waiting for unfinished jobs....
...
```

https://gist.github.com/2a6044e16ce9dd98494930f61c8c1b00

cc @staticfloat

**Comment by appleparan** [comment]
Did you install Xcode command line tools?

**Comment by tdsmith** [comment]
Yes.

**Comment by appleparan** [comment]
Sorry for deleting comments, because I upgraded julia successfully by homebrew. It seems Xcode problem. I found similar issue on Yosemite beta, https://github.com/JuliaLang/julia/issues/7762 . Please reinstall command line tools only by ```xcode-select --install``` command or reinstall Xcode and command line tools again.

**Comment by BenjaminBorn** [comment]
I have a similar problem installing Julia 0.5 via Homebrew. System freshly updated to macOS Sierra. Command line tools reinstalled after update. Homebrew updated to 1.0.0.

```
Last 15 lines from /Users/benjaminborn/Library/Logs/Homebrew/julia/02.make:
100  118k  100  118k    0     0  71013      0  0:00:01  0:00:01 --:--:--  175k
100  147k  100  147k    0     0  81856      0  0:00:01  0:00:01 --:--:--  182k
make[2]: Circular src/libuwind.cxx <- src/libuwind.cxx.o dependency dropped.
100  344k  100  344k    0     0   170k      0  0:00:02  0:00:02 --:--:--  347k
  0  284k    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0ld: archive has no table of contents file 'libosxunwind.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libosxunwind.dylib] Error 1
make[2]: *** Waiting for unfinished jobs....
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libosxunwind.a(Unwind-sjlj.c.o) has no symbols
make[1]: *** [build/libosxunwind-0.0.3/libosxunwind.dylib] Error 2
make[1]: *** Waiting for unfinished jobs....
ar: creating archive libutf8proc.a
100 1378k  100 1378k    0     0   548k      0  0:00:02  0:00:02 --:--:--  931k
100  284k  100  284k    0     0   101k      0  0:00:02  0:00:02 --:--:--  424k
make: *** [julia-deps] Error 2
```

**Comment by staticfloat** [comment]
Hmmm, on a clean VM with XCode installed, I did not run into this problem.  Did any of you upgrade, or did you all do clean installations of OSX 10.12?  If you upgraded, please remove all dependencies and install again from scratch, e.g. `brew rm $(brew deps julia)`.

**Comment by BenjaminBorn** [comment]
I upgraded to mac OS 10.12 from El Capitan. Reinstalled command line tools afterwards. Removing all dependencies and installing again from scratch yields the same error. Reinstalling homebrew from scratch also doesn't help.

**Comment by BenjaminBorn** [comment]
Ok, reinstalling Sierra on a clean system solved the problem. Don't know what the problem was but probably something in the upgrade from El Capitan to Sierra went wrong.

Thanks again for looking into this.

**Comment by tdsmith** [comment]
It started working for me, so ¯\\\_(ツ)\_/¯ Sorry for the noise.

**Comment by staticfloat** [comment]
I'm never too upset when my software starts working on another's computer again!  Thanks for the report, and don't hesitate to open further issues if you have problems.
