### ISSUE TITLE
ld: library not found for -lLLVM

### ISSUE THREAD

**Issue by sononix** [staticfloat/homebrew-julia#232]
trying to install against HEAD
brew install --HEAD julia

ld: library not found for -lLLVM
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/private/tmp/julia-20170202-64866-18afq0f/usr/lib/libjulia.0.6.0.dylib] Error 1
make: *** [julia-src-release] Error 2

gcc -v

COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/6.3.0_1/libexec/gcc/x86_64-apple-darwin16.3.0/6.3.0/lto-wrapper
Target: x86_64-apple-darwin16.3.0
Configured with: ../configure --build=x86_64-apple-darwin16.3.0 --prefix=/usr/local/Cellar/gcc/6.3.0_1 --libdir=/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-6 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 6.3.0_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 6.3.0 (Homebrew GCC 6.3.0_1)

anything I should be trying 
tks

**Comment by staticfloat** [comment]
Thanks for reporting this, please `brew update` and try again.
