### ISSUE TITLE
brew link with multiple versions of julia

### ISSUE THREAD

**Issue by jpfairbanks** [staticfloat/homebrew-julia#235]
Hi @staticfloat,

Thanks for making these builds so accessible.

I would like to have different major versions of julia installed at the same time for instance `julia4, julia5, julia6` pointing to builds at version `4.6, 5.0.1, and 6.0-dev` respectively. When I install them through homebrew the `brew link` step fails because the different versions want to install at the same place `/usr/bin/julia`. Is there a way to modify the homebrew ruby file to add these aliases?

Would you be open to adding this as a feature accessed with a command line flag such as `--version-alias`?

I recently switched to using homebrew for my julia installs. Previously, I just built from source and added bash aliases to get the different versions.

**Comment by staticfloat** [comment]
Hey @jpfairbanks,

I think this is going to work best with you just leaving the multiple versions of `julia` unlinked, then directly invoking their executables from the cellar.  E.g. you can have bash aliases that point to `/usr/local/Cellar/julia/0.5.0/bin/julia` and run Julia straight from there.

The problem with having multiple versions linked goes beyond just the executable name.  There are library folders that would conflict as well, although that is fixable (by changing the formula to link in only the executable files, and aliasing to a separate version).

Would the "leave unlinked and use a bash alias for all other versions" solution work for you?

**Comment by jpfairbanks** [comment]
> There are library folders that would conflict as well

Is this relevant for people who have C code that links to `libjulia`?
How do they manage multiple version? By setting load paths in their build systems?

I can just keep on using bash aliases.

**Comment by staticfloat** [comment]
> Is this relevant for people who have C code that links to libjulia?

Yes, in general, those kinds of tools must be configured to find libjulia.  There are, of course, default paths that it can search, but for any kind of multi-version setup the user will most likely need to configure it manually.
