### ISSUE TITLE
Unable to install Julia with or without --HEAD

### ISSUE THREAD

**Issue by dfings** [staticfloat/homebrew-julia#236]
Without --HEAD:

$ brew install julia
==> Installing julia from staticfloat/julia
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/JuliaLang/julia.git
Updating /Users/user/Library/Caches/Homebrew/julia--git
==> Checking out tag v0.5.0
Cloning into '/private/tmp/julia-20170221-46901-6oi2xa'...
done.
Note: checking out '3c9d75391c72d7c32eea75ff187ce77b2d5effc8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Downloading https://gist.githubusercontent.com/timxzl/c6f474fa387382267723/raw/2ecb0270d83f0a167358ff2a396cd6004e1b02a0/Makefile.diff
######################################################################## 100.0%
==> Patching
==> Applying Makefile.diff
patching file Makefile
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 286 with fuzz 1 (offset 14 lines).
==> make -C contrib -f repackage_system_suitesparse4.make prefix=/Users/user/homebrew/Cellar/julia/0.5.0 USE_BLAS64=0 TAGGED_RELEASE_BANNER="homebrew-julia re
==> make prefix=/Users/user/homebrew/Cellar/julia/0.5.0 USE_BLAS64=0 TAGGED_RELEASE_BANNER="homebrew-julia release" FC=/Users/user/homebrew/bin/gfortran LL
Last 15 lines from /Users/user/Library/Logs/Homebrew/julia/02.make:
strings/types.jl
strings/basic.jl
strings/search.jl
strings/util.jl
strings/io.jl
strings/utf8proc.jl
parse.jl
shell.jl
regex.jl
pcre.jl
show.jl
LoadError("sysimg.jl",152,LoadError("show.jl",1238,ErrorException("error compiling Type: error compiling Type: error compiling compile: error compiling compile: could not load library \"libpcre2-8\"\ndlopen(libpcre2-8.dylib, 1): image not found")))
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/private/tmp/julia-20170221-46901-6oi2xa/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/staticfloat/homebrew-julia/issues

With --HEAD:

$ brew install julia --HEAD
==> Installing julia from staticfloat/julia
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/JuliaLang/julia.git
Updating /Users/user/Library/Caches/Homebrew/julia--git
==> Checking out branch master
Cloning into '/private/tmp/julia-20170221-16345-12rzk1p'...
done.
==> Downloading https://gist.githubusercontent.com/timxzl/c6f474fa387382267723/raw/2ecb0270d83f0a167358ff2a396cd6004e1b02a0/Makefile.diff
######################################################################## 100.0%
==> Patching
==> Applying Makefile.diff
patching file Makefile
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 286 with fuzz 1 (offset 14 lines).
==> make -C contrib -f repackage_system_suitesparse4.make prefix=/Users/user/homebrew/Cellar/julia/HEAD-61a291b USE_BLAS64=0 TAGGED_RELEASE_BANNER="homebrew-j
==> make prefix=/Users/user/homebrew/Cellar/julia/HEAD-61a291b USE_BLAS64=0 TAGGED_RELEASE_BANNER="homebrew-julia release" FC=/Users/user/homebrew/bin/gfor
Last 15 lines from /Users/user/Library/Logs/Homebrew/julia/02.make:
do_call at /private/tmp/julia-20170221-16345-12rzk1p/src/interpreter.c:75
eval at /private/tmp/julia-20170221-16345-12rzk1p/src/interpreter.c:230
jl_interpret_toplevel_expr at /private/tmp/julia-20170221-16345-12rzk1p/src/interpreter.c:34
jl_toplevel_eval_flex at /private/tmp/julia-20170221-16345-12rzk1p/src/toplevel.c:577
jl_eval_module_expr at /private/tmp/julia-20170221-16345-12rzk1p/src/toplevel.c:203
jl_toplevel_eval_flex at /private/tmp/julia-20170221-16345-12rzk1p/src/toplevel.c:480
jl_parse_eval_all at /private/tmp/julia-20170221-16345-12rzk1p/src/ast.c:872
jl_load at /private/tmp/julia-20170221-16345-12rzk1p/src/toplevel.c:616
exec_program at /private/tmp/julia-20170221-16345-12rzk1p/usr/bin/julia (unknown line)
true_main at /private/tmp/julia-20170221-16345-12rzk1p/usr/bin/julia (unknown line)
main at /private/tmp/julia-20170221-16345-12rzk1p/usr/bin/julia (unknown line)

*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/private/tmp/julia-20170221-16345-12rzk1p/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/staticfloat/homebrew-julia/issues

@staticfloat

**Comment by dfings** [comment]
Digging into the log the error for --HEAD is actually the same as without.

LoadError(at "sysimg.jl" line 174: LoadError(at "show.jl" line 1305: ErrorException("error compiling Type: error compiling Type: error compiling compile: error compiling compile: could not load library "libpcre2-8"
dlopen(libpcre2-8.dylib, 1): image not found")))

I've tried uninstalling and reinstalling pcre, with and without --universal.

**Comment by staticfloat** [comment]
Is your Homebrew in a non-standard location?  Do you know why Homebrew is not installing bottles?

**Comment by dfings** [comment]
My homebrew is under /Users/$username/homebrew.

I've installed lots of other bottles with no problem, so not sure why this one isn't working.

What I don't see is libpcre2-8.dynlib in /usr/lib, maybe that's the issue?

$ ls homebrew/Cellar/pcre2/10.22/lib/
libpcre2-16.0.dylib     libpcre2-32.0.dylib     libpcre2-8.0.dylib      libpcre2-posix.1.dylib  pkgconfig/
libpcre2-16.a           libpcre2-32.a           libpcre2-8.a            libpcre2-posix.a
libpcre2-16.dylib@      libpcre2-32.dylib@      libpcre2-8.dylib@       libpcre2-posix.dylib@

$ ls /usr/lib/libpcre*
/usr/lib/libpcre.0.dylib*      /usr/lib/libpcre.dylib@        /usr/lib/libpcreposix.0.dylib* /usr/lib/libpcreposix.dylib@

**Comment by staticfloat** [comment]
@dfings can you try editing the `julia.rb` file, (e.g. `brew edit julia`) and changing [this line](https://github.com/staticfloat/homebrew-julia/blob/5e0c3d23c60073ad32842d547c64e4e64c3e8d3f/julia.rb#L125) and [this line](https://github.com/staticfloat/homebrew-julia/blob/5e0c3d23c60073ad32842d547c64e4e64c3e8d3f/julia.rb#L144) to read `libpcre2-8.dylb` instead of `libpcre2-8.0.dylib`?  Then try rebuilding.

**Comment by dfings** [comment]
That solved the error I was running into. Though it's still not completing. Now I'm getting:

LoadError("sysimg.jl",326,LoadError("libgit2/libgit2.jl",13,LoadError("libgit2/consts.jl",282,ErrorException("error compiling version: could not load library \"libgit2\"\ndlopen(libgit2.dylib, 1): image not found"))))

@staticfloat

**Comment by staticfloat** [comment]
Thanks, I've included that patch in the repo now.

Do you have `libgit2` linked?  Is there a `libgit2.dylib` in your brew's `lib` directory?

**Comment by dfings** [comment]
I do seem to have libgit2 in my brew's lib directory.

$ ls -la homebrew/lib/libgit2.dylib
homebrew/lib/libgit2.dylib@ -> ../Cellar/libgit2/0.25.1/lib/libgit2.dylib
$ ls -la homebrew/Cellar/libgit2/0.25.1/lib/libgit2.dylib
homebrew/Cellar/libgit2/0.25.1/lib/libgit2.dylib@ -> libgit2.25.dylib
$ ls -la homebrew/Cellar/libgit2/0.25.1/lib/libgit2.25.dylib
homebrew/Cellar/libgit2/0.25.1/lib/libgit2.25.dylib@ -> libgit2.0.25.1.dylib
$ ls -la homebrew/Cellar/libgit2/0.25.1/lib/libgit2.0.25.1.dylib
homebrew/Cellar/libgit2/0.25.1/lib/libgit2.0.25.1.dylib

@staticfloat

**Comment by dfings** [comment]
I should note that I also have both homebrew/lib/libpcre2-8.dylib and libpcre2-8.0.dylib in my homebrew/lib directory. What I reported before is neither of them were in /usr/lib.

Why did changing from libpcre2-8.0.dylib instead of libpcre2-8.dylb move me past that error when both are in homebrew/lib?

**Comment by staticfloat** [comment]
@dfings Honestly, looking back at it, I have no idea why that would make a difference, and I doubt it did; I think there must have been something else going on.

I was able to replicate your issue, and I think I worked around it properly on [this branch](https://github.com/staticfloat/homebrew-julia/tree/fix_head).  Please go to the tap directory (`homebrew/Library/Taps/staticfloat/homebrew-julia`), `git fetch` then `git checkout fix_head`.  If it complains that there is no branch called `fix_head` you probably need to "unshallow" your git clone, you can do so with `brew tap --full staticfloat/julia`.

**Comment by dfings** [comment]
That seems to have worked! The first time I ran `brew install julia` after that I got a weird error:

 20 1378k   20  288k    0     0  71254      0  0:00:19  0:00:04  0:00:15  276k/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libosxunwind.a(Unwind-sjlj.c.o) has no symbols
ld: archive has no table of contents file 'libosxunwind.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

But when I ran it the second time it completed successfully and I can run Julia programs.

@staticfloat

**Comment by staticfloat** [comment]
Thanks @dfings, that error sometimes pops up, don't worry too much about it.  I've integrated your changes into the main repository, thanks for your reports!
