### ISSUE TITLE
How to remove julia completely from my system?

### ISSUE THREAD

**Issue by kirk86** [staticfloat/homebrew-julia#246]
@staticfloat Please could you let us know how to completely remove julia from our systems.
I've tried `brew uninstall --ignore-dependencies --force $(brew deps --recursive julia)` but when I do `which julia` it gives me: `/usr/loca/bin/julia -> Cellar/julia/HEAD/bin/julia`. So what is the correct way to completely remove julia from our systems?

**Comment by staticfloat** [comment]
Permission denied just means that your permissions are somehow screwed up.  Try running this first:

```
$ chown $(id -u):$(id -g) -R /usr/local/Cellar/julia
```

Then run it again.

**Comment by kirk86** [comment]
@staticfloat thanks a lot for the hint. The `chown` command didn't do the trick but the `chmod -R 755` did it and the `brew uninstall` worked fine. Thanks!
