### ISSUE TITLE
Can't load module libopenblas

### ISSUE THREAD

**Issue by bjarkehs** [staticfloat/homebrew-julia#76]
I get the following error when I run julia on a clean installation:

```
Warning: error initializing module LinAlg:
ErrorException("could not load module libopenblas: dlopen(libopenblas.dylib, 1): image not found")
```

I googled it and found this issue on Julia's Rmath module where the same error occurs:
https://github.com/JuliaLang/Rmath/issues/3

The problem seems to be that julia doesn't install it as a dependency, because @staticfloat asked if the following command could be run `otool -L /usr/local/lib/libopenblas.dylib`. When I did this I received:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /usr/local/lib/libopenblas.dylib (No such file or directory)
```

My installation was done with `brew install --HEAD --64bit julia` and it seems like the openblas dependency isn't installed with julia.

**Comment by scott-maddox** [comment]
To summarize, the following one-liner should fix this problem:

    brew rm --force gcc gfortran openblas-julia arpack-julia suite-sparse-julia && brew update && brew install julia

**Comment by hayd** [comment]
@scott-maddox Thanks, this hit me too.

**Comment by kirk86** [comment]
I cannot uninstall julia, keep getting the following error:

```
rew uninstall julia
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/julia.rb:40:in `<class:Julia>'
Please report this to the staticfloat/julia tap!

Error: Permission denied @ rb_file_s_lstat - /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib.dSYM/Contents
```
