### ISSUE TITLE
"new" file not found

### ISSUE THREAD

**Issue by tmcw** [staticfloat/homebrew-julia#92]
Getting this error log when I'm trying to install Julia: https://gist.github.com/f0ce5eea3aaaab332ce6

The gist is:

```
checking for gcc... clang -stdlib=libc++ -mmacosx-version-min=10.7
src/libuwind.cxx:28:10: fatal error: 'new' file not found
#include <new>
         ^
```

**Comment by idinev2** [comment]
It's a bad local installation of GCC. Make a simple file, that has "#include <new>". Then run like this:
clang++ test.cpp --verbose
See at the top: 
```
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.1.0
```
Here your gcc 5.1.0 is damaged/bad. I bet you can't apt-get uninstall it, as APT doesn't know about it. Manually remove its folders. Try clang++ again, it'll select a different GCC installation and finally compile the file.
Cheers.
